// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGrQXxkXdscs8AaRIVVxhp7HbV25NiPI',
    appId: '1:668392084379:web:c0327f44e8e8cc22bec73e',
    messagingSenderId: '668392084379',
    projectId: 'do-an-huy',
    authDomain: 'do-an-huy.firebaseapp.com',
    storageBucket: 'do-an-huy.appspot.com',
    measurementId: 'G-CNTK1T3RF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpe7cR8OnZTeOCsjHGC7yBZfWVUrQLrAE',
    appId: '1:668392084379:android:9221bfb3e18f0d54bec73e',
    messagingSenderId: '668392084379',
    projectId: 'do-an-huy',
    storageBucket: 'do-an-huy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAacwo96THk1AR_GnGrhplAPc35NpJc61I',
    appId: '1:668392084379:ios:1bf342da5e165fdbbec73e',
    messagingSenderId: '668392084379',
    projectId: 'do-an-huy',
    storageBucket: 'do-an-huy.appspot.com',
    iosBundleId: 'com.example.doAnFlutter',
  );
}
